### ISSUE TITLE
Guidelines for Codestyle / package names

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/basement-gnu-linux#42]
Hi,
I have "some" [new recipes](https://github.com/user-attachments/files/17813305/new_recipes.txt) I'd like to upstream in the next days, weeks, months, ... As we're using `git`-scms I need to rework them first to use url-scms, but in addition to that I fear package names / paths do not match your expectations. It would be helpful have some kind of contributor guidelines / "where should I place my recipes" guide to avoid renamings, ...

In addition to that I think having some code-style specifications would be also helpful. For our recipes we're using https://pre-commit.com/ with https://github.com/google/yamlfmt which works well. Do you think this is useful / helpful?  I can come up with a PR for this.

**Comment by jkloetzke** [comment]
These are a lot of recipes. Thanks in advance already for brining them upstream. I guess we'll have to add some automated builds in the future to make sure things don't break. But this is another discussion.

Regarding some documentation about the recipes, their category, coding style and so on it perfectly makes sense to start some documentation. I have to admit this is not in any way settled. We also need some documentation how to use the existing recipes. I'll try to create a skeleton in the next days. I would put this documentation in the basement repository, though. There we already imply a directory layout and the basement-gnu-linux layer is just a natural extension.

Regarding the automated YAML coding style checking it really depends on the behaviour tool. At a first glance this sounds like a good idea. Except for the pre commit hook we should run some Github action on a PR to check for the style. I would be open to give it a try.

**Comment by mahaase** [comment]
we have recipes for open-source libraries like boost, qt5, a.s.o. too. I would try to compare them with our ones, may in case we can make them more flexible and/or robust. maybe there are some more libraries not in ur list we could provide.

would extremly love it, if the recipe support would increase! this is one of the most important points for end users I guess.

**Comment by rhubert** [comment]
> These are a lot of recipes. Thanks in advance already for brining them upstream. I guess we'll have to add some automated builds in the future to make sure things don't break. But this is another discussion.

This is also a very good point. Maybe we should start another issue for this?

> Regarding the automated YAML coding style checking it really depends on the behaviour tool. At a first glance this sounds like a good idea. Except for the pre commit hook we should run some Github action on a PR to check for the style. I would be open to give it a try.

I pushed a first shot for the codestyle checking: https://github.com/BobBuildTool/basement/pull/233 

For github it should just work: https://pre-commit.ci/  Not sure if it needs to be activated somewhere in the repo settings?

**Comment by jkloetzke** [comment]
I've created a first draft. See the [recipe naming](https://github.com/BobBuildTool/basement/blob/ce8c0def35232eaab32b22331353c8e1b3ba9df6/doc/contribution.rst#recipe-naming) section in particular. As I said, nothing is set in stone. Naming is hard and I don't have a good track record in this respect so far. :laughing:

**Comment by jkloetzke** [comment]
The docs are now online at https://bob-build-tool.readthedocs.io/projects/basement/en/latest/index.html
