### ISSUE TITLE
layer name

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement-gnu-linux#7]
isn't that layer wrong named. i guess it should be `basement-linux-gnu`, shouldn't it? 😁

**Comment by jkloetzke** [comment]
I don't think so. On most part this layer is about GNU software on a Linux kernel, like in GNU/Linux. Hence the name. In any case I would not do a rename for such a reason.

**Comment by mahaase** [comment]
just kidding! i type it so often wrong, i guess because of `x86_64-linux-gnu` crosss-toolchain naming 😉
